# Site settings
title: TW-4 Course Rules
email: ejm29@case.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://courserules.github.io" # the base hostname & protocol for your site
#url: "http://localhost:4000"
#twitter_username: dmcwru
github_username:  tamfr
timezone: America/Chicago

# Build settings
markdown: kramdown
